DEFAULT_VERSION='0.0.1'

# shellcheck disable=SC2034
MAVEN_REVISION=${VERSION:-"$DEFAULT_VERSION-SNAPSHOT"}
# shellcheck disable=SC2034
DOCKER_REVISION=${VERSION:-"$DEFAULT_VERSION"}
TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}
TROXY_DOCKER_IMAGE=${TROXY_DOCKER_IMAGE:-'troxy'}
