DEFAULT_VERSION='0.0.1'
TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}

# Override VERSION when building a pull request
if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then
    unset VERSION
fi

# shellcheck disable=SC2034
MAVEN_REVISION=${VERSION:-"$DEFAULT_VERSION-SNAPSHOT"}

# shellcheck disable=SC2034
DOCKER_REVISION=${VERSION:-"$DEFAULT_VERSION"}
TROXY_DOCKER_IMAGE=${TROXY_DOCKER_IMAGE:-'troxy'}

if [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then
    MAVEN_REVISION="$MAVEN_REVISION.$TRAVIS_BUILD_NUMBER"
    DOCKER_REVISION="$DOCKER_REVISION.$TRAVIS_BUILD_NUMBER"
fi
