VERSION='3.2'

TROXY_DOCKER_IMAGE='sparebank1/troxy'

MAVEN_REVISION=${VERSION-SNAPSHOT}

DOCKER_REVISION=${VERSION}
TROXY_DOCKER_IMAGE=${TROXY_DOCKER_IMAGE:-'troxy'}

MAVEN_REVISION="$MAVEN_REVISION.$GITHUB_RUN_NUMBER"
DOCKER_REVISION="$DOCKER_REVISION.$GITHUB_RUN_NUMBER"